apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/mayur-g-nimavat-capgemini-com/godemocicd:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/mayur-g-nimavat-capgemini-com/godemocicd:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: godemocicd
        chartPath: charts/godemocicd
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/mayur-g-nimavat-capgemini-com/godemocicd'
          image.tag: '{{.DIGEST_HEX}}'
